# Generated by Django 2.2.4 on 2019-08-10 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KVForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='KVInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KVKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='KVType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('django_type', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=100)),
                ('basic_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='KVValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_integer', models.IntegerField(blank=True, default=None, null=True)),
                ('value_boolean', models.NullBooleanField(default=None)),
                ('value_text', models.TextField(blank=True, default='', null=True)),
                ('value_float', models.FloatField(blank=True, default=None, null=True)),
                ('value_file', models.FloatField(blank=True, default=None, null=True)),
                ('value_choice', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kv_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvform.KVInstance')),
                ('kv_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvform.KVKey')),
            ],
        ),
        migrations.AddField(
            model_name='kvkey',
            name='kv_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvform.KVType'),
        ),
    ]
