# Generated by Django 2.2.4 on 2019-08-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvform', '0003_kvkey_kv_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvkey',
            name='blank',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kvkey',
            name='null',
            field=models.BooleanField(default=False),
        ),
    ]
