# Generated by Django 2.2.4 on 2019-11-10 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kvform', '0004_auto_20190812_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvinstance',
            name='kv_form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kvform.KVForm'),
            preserve_default=False,
        ),
    ]
