# Generated by Django 4.1 on 2023-01-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvform', '0005_kvinstance_kv_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvvalue',
            name='value_boolean',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
