# Generated by Django 5.0.1 on 2024-01-13 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvform', '0006_alter_kvvalue_value_boolean'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KVKey',
            new_name='KVField',
        ),
        migrations.RenameModel(
            old_name='KVForm',
            new_name='KVModelName',
        ),
        migrations.RenameModel(
            old_name='KVInstance',
            new_name='KVRecord',
        ),
        migrations.RenameField(
            model_name='kvfield',
            old_name='kv_form',
            new_name='kv_model',
        ),
    ]
